### PR TITLE
Delete dead link from README.md

### PR DESCRIPTION
**Pull request by Zaptyp**
Delete dead link from README.md

### CODE REVIEW

**Comment by Jacob1Tm** [comment]
ale to z 2137 to było celowo zostawione...

**Comment by Zaptyp** [comment]
> ale to z 2137 to było celowo zostawione...

What?
I don't understand you.

**Comment by Jacob1Tm** [comment]
> > ale to z 2137 to było celowo zostawione...
> 
> What? I don't understand you.

w tym memie chodzi o to że to godzina papieżowa

**Comment by Zaptyp** [comment]
> > > ale to z 2137 to było celowo zostawione...
> > 
> > 
> > What? I don't understand you.
> 
> w tym memie chodzi o to że to godzina papieżowa.

Please use English

**Comment by Jacob1Tm** [comment]
> > > > ale to z 2137 to było celowo zostawione...
> > > 
> > > 
> > > What? I don't understand you.
> > 
> > 
> > w tym memie chodzi o to że to godzina papieżowa.
> 
> Please use English

oh ok thats meme in poland

**Comment by Zaptyp** [comment]
> > > > > ale to z 2137 to było celowo zostawione...
> > > > 
> > > > 
> > > > What? I don't understand you.
> > > 
> > > 
> > > w tym memie chodzi o to że to godzina papieżowa.
> > 
> > 
> > Please use English
> 
> oh ok thats meme in poland

A ok

**Review by fratik — APPROVED** [review]
good catch, thanks

also fyi, please don't include other changes (talking about the `lub 11` here) in a PR about a dead link
gonna merge anyway, because you're correct: Java 11 is now being used in production and it works

**Pull request merged**
